/* eslint-disable max-len */
// eslint-disable-next-line import/prefer-default-export
export const projects = [
  {
    index: 0,
    Title: 'Spotify Profile Action',
    Type: 'Pet project',
    Description: 'A web application for visualizing personalized Spotify data using Spotify API with Neumorphism design system. A user can view their top artists, top tracks of all time, playlist and recent tracks.',
    Tags: 'React Js,Webpack, Express, Neumorphism UI, Spotify API',
    Demo: 'http://spotify-profile-actions.herokuapp.com/',
    Repo: 'https://github.com/praveengopi19/spotify-profile-actions',
  },
  {
    index: 1,
    Title: 'Personal Resume Website Builder',
    Type: 'Pet project',
    Description: 'A web application to create an online personal resume/portfolio website using HTML forms. The features include creating n number of inputs for a particular field, preview their personal resume website at the time of creation, and can download the resultant website source code files as Zip file format.',
    Tags: 'HTML, CSS, JavaScript',
    Demo: 'https://praveengopi19.github.io/Personal-Resume-Website-Builder',
    Repo: 'https://github.com/praveengopi19/Personal-Resume-Website-Builder',
  },
  {
    index: 2,
    Title: 'Portfolio',
    Type: 'Pet project',
    Description: 'Interactive Command Line Interface and Minimal Portfolio site built with caching assets and offline detection using ServiceWorker (Progressive Web Application) and coded from scratch to showcase my skills and past work.',
    Tags: 'HTML, CSS, JavaScript',
    Demo: 'https://praveengopi19.github.io/',
    Repo: '#',
  },
  {
    index: 3,
    Title: 'Attendance Management system',
    Type: 'Pet project',
    Description: 'A web application to note down the presence and absence of the student. The features include assigning the task(class) for staff and he/she can take and edit the presence and absence of the student.',
    Tags: 'HTML, BootStrap, JavaScript, PHP, MySQL',
    Demo: '#',
    Repo: 'https://github.com/praveengopi19/Attendance-Application',
  },
  {
    index: 4,
    Title: 'Trafalgar',
    Type: 'Pet project',
    Description: 'Responsive Landing page for Virtual healthcare system. This web page was developed with reference UI, designed in Figma. The main goal of this website is to get practice in developing web page from UI design.',
    Tags: 'HTML, CSS, JavaScript',
    Demo: 'https://praveengopi19.github.io/Trafalgar/',
    Repo: 'https://github.com/praveengopi19/Trafalgar',
  },
  {
    index: 5,
    Title: 'To Do List',
    Type: 'Pet project',
    Description: 'A web application to add and track the daily task. The tasks are stored in browser local storage, thus one track daily task by running a single HTML file rather than using it in online.',
    Tags: 'HTML, CSS, JavaScript, LocalStorage',
    Demo: 'https://praveengopi19.github.io/To-Do-List/',
    Repo: 'https://github.com/praveengopi19/To-Do-List',
  },
];

// const project = [{
//   index: 0,
//   Title: 'FingerPrint based Voting system',
//   Type: 'Team',
//   Description: 'An IoT project which prevents the electoral fraud during voting by casting votes through their fingerprint.',
//   Mycontribution: 'Hardware interfacing.',
//   Tags: 'IoT, Arduino',
// }, {
//   index: 1,
//   Title: 'Automatic detection of accident vehicles',
//   Type: 'Team',
//   Description: ' Automatically detects the accident and alerts the nearby hospital to reach the spot to rescue the person within the golden hours.',
//   Mycontribution: 'Developed two android application one for fetching location and another for displaying details of the accident vehicle.',
//   Tags: 'IoT, Android, Java, Arduino',
// }, {
//   index: 2,
//   Title: 'Agri Market ( Crop selling website for farmers )',
//   Type: 'Team',
//   Description: 'A Web application which connect the farmers and the consumers for buying and selling agricultural products and therby eliminates the need for middle man.',
//   Mycontribution: 'Devloped the frontend part of the whole application.',
//   Tags: 'HTML, CSS, JavaScript, PHP, MySQL',

// }, {
//   index: 3,
//   Title: 'Interference mitigation in WBAN using Game theory',
//   Type: 'Team',
//   Description: 'The effective allocation of resources in Wireless Body Area Network (WBAN) to migitage interference by means of using Game Theory.',
//   Mycontribution: 'Expolring and implementaion of Game theory and interfacing the HardWare setup.',
//   Tags: 'MATLAB, Arduino, IoT',
// },
// {
//   index: 4,
//   Title: 'Attendance Management system',
//   Type: 'Pet project',
//   Description: 'A web application to update the daily presensce and absence of the student.',
//   Tags: 'HTML, BootStrap, JavaScript, PHP, MySQL',
// },
// {
//   index: 5,
//   Title: 'To Do List',
//   Type: 'Pet project',
//   Description: 'A web application to add and track the daily task using local storage of the browser.',
//   Tags: 'HTML, CSS, JavaScript, Browser LocalStorage',
// },
// ];
